name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executables or extension modules from Python projects
      uses: Nuitka/Nuitka-Action@v1.1
      with:
        python-version: ${{ matrix.python-version }}
        script: your_script.py  # Adjust this to your main script

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: ./*.dist
